# Generated by Django 3.2.7 on 2021-09-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogposts',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=12000)),
                ('image', models.ImageField(default='', upload_to='home/images')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('srno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('issue', models.TextField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
