# Generated by Django 3.2.7 on 2021-09-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abhi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='subtitle',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='title',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
