# Generated by Django 3.2.7 on 2021-09-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abhi', '0002_alter_blogposts_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='image',
            field=models.ImageField(default='', upload_to='media/home/images'),
        ),
    ]
