# Generated by Django 3.2.7 on 2021-09-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abhi', '0004_auto_20210913_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposts',
            name='slug',
        ),
        migrations.AddField(
            model_name='blogposts',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
