# Generated by Django 3.2.7 on 2021-09-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abhi', '0005_auto_20210914_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
